theme: jekyll-theme-slate
title: IoT-Router Convention
description: An agreement between interested parties covering positions, definitions and specifications for MQTT applications in a harmonised way.
